### ISSUE TITLE
Tilesets API

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/bigmetadata#469]
- [x] Generate and visualize MVT files using Postgis 2.4 function for:
  - Polygons
  - Points
- [x] Generate and visualize MVT files using Quadtree geometries for:
  - Polygons
  - Points
- [x] Measure performance
- [x] Set up a running environment.
  - [x] Request API 
- [x] Kickoff meeting.
- [x] XYZ tables (blocking until actual needs are known ~and new scripts are received~)
  - [x] Generate XYZ table with all the needed information
  - [x] Use parallelization to improve the performance
  - [x] Add the requested columns for DO in USA (#498)
  - [x] Support multiple countries
  - [x] Adapt Geographica ETL scripts to DO ETL.
  - [x] Review Geographica shapes.
    - [x] Add new needed shapes.
    - [x] Discuss conflicts.
  - [x] Split the XYZ table into 3+ different tables if necessary (#496)
  - [x] Add the 'category' to the XYZ table (~probably not necessary~) (#497 #516)
  - [x] [Generate all the zoom levels](https://github.com/CartoDB/observatory-extension/issues/342)
- [X] Retrieve MVT either from pregenerated table or from function.
  - [x] Fix holes error at zoom level 4.
  - [x]  Fix asMVT orientation in Postgis (@ethervoid https://github.com/CartoDB/postgis/issues/18)
  - [x] Fix projection (@antoniocarlon ).
  - [ ] Add more boundaries for some countries (Uk, Spain, Australia) (@ethervoid #503 , blocked waiting for info)
  - [x] Improve function retrieval performance (CartoDB/observatory-extension#336) (@antoniocarlon, @ethervoid  )
  - [x] What to do with zoom 14 and block for ACS (#505) (@ethervoid )
  - [x] Tiger blocks simplification by state (#512)
  - [x] Check Zip code data output from the MVT function (#518) (@antoniocarlon)
  - [x] Return geometry area in the function (https://github.com/CartoDB/observatory-extension/issues/341) (@antoniocarlon)
- [x] Provide a CSV with needed measurements to Geographica: #508 (@ethervoid ).
  - [x] Interpolate block group ACS data into block boundary (#505)
  - [x] Provide Zip code data
- [x] Provide a CSV with needed measurements to Geographica _nice to haves_.
  - [x] Add state and county level for Zillow (#510)
  - [x] Interpolate block and block_group from census tract in spielman singleton (#511)
- [x] Answer whether we must provide MBTiles server infrastructure.
- CARTO-VL enhancements:
  - [x] MVT source (CartoDB/carto-vl#487 - @ethervoid)
- [x] Tilesets API Deployment: CartoDB/do_tiler/issues/2
  - [x] MVT slowness and fixes: CartoDB/bigmetadata/issues/541
  - [x] Dynamic query
  - [x] Basic API key support
  - [x] URL and parameters: CartoDB/do_tiler/issues/4 ; measurement sets, individual measurements, time frames.
  - [x] First deployment
  - [x] Check metrics
  - [x] https
  - [x] Move MVT generation to Node
  - [x] Use good behaviour (nicely simplified) blocks
